### ISSUE TITLE
Error: apiContext has not been loaded.

### ISSUE THREAD

**Issue by jagdishkaler** [bunq/sdk_php#128]
By following this example, when I calling data from bunq.conf file and try to get user. I am getting error, "apiContext has not been loaded.", I dont know what I am doing wrong here. 
Can anyone help me out please?
@OGKevin

**Comment by jagdishkaler** [comment]
here is code and error:
![error](https://user-images.githubusercontent.com/36437555/38419701-0a1db4dc-39bf-11e8-8b8e-9a7b3f78704c.png)

![code](https://user-images.githubusercontent.com/36437555/38419713-14aee376-39bf-11e8-8910-d80eb49f67a9.png)

**Comment by mbernson** [comment]
Hello @jagdishkaler,

You're probably getting this error because you used the sample code from the SDK, which is outdated at this moment. 🤦‍♂️

You can fix it by adding the following line right after you've set up your ApiContext:

```
BunqContext::loadApiContext($apiContext);
```

To get sample code that **does** work, try our new API tinker project. It only takes one command to install and set up: https://www.bunq.com/developer

**Comment by jagdishkaler** [comment]
Hey @mbernson thanks for reply,
My i get full code example ? Thanks.
